// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// OptimizeMICL
S4 OptimizeMICL(S4 reference, StringVector name);
RcppExport SEXP _VarSelLCM_OptimizeMICL(SEXP referenceSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< StringVector >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(OptimizeMICL(reference, name));
    return rcpp_result_gen;
END_RCPP
}
// ComputeMICL
S4 ComputeMICL(S4 reference, StringVector name);
RcppExport SEXP _VarSelLCM_ComputeMICL(SEXP referenceSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< StringVector >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeMICL(reference, name));
    return rcpp_result_gen;
END_RCPP
}
// OptimizePenLike
S4 OptimizePenLike(S4 reference, double pen);
RcppExport SEXP _VarSelLCM_OptimizePenLike(SEXP referenceSEXP, SEXP penSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< double >::type pen(penSEXP);
    rcpp_result_gen = Rcpp::wrap(OptimizePenLike(reference, pen));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VarSelLCM_OptimizeMICL", (DL_FUNC) &_VarSelLCM_OptimizeMICL, 2},
    {"_VarSelLCM_ComputeMICL", (DL_FUNC) &_VarSelLCM_ComputeMICL, 2},
    {"_VarSelLCM_OptimizePenLike", (DL_FUNC) &_VarSelLCM_OptimizePenLike, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_VarSelLCM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
